//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string Post { get; set; }
        public string Description { get; set; }
        public string Experience { get; set; }
        public int Bonus { get; set; }
        public Nullable<int> Vacancy { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
