//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PurpleSquirrelEntities : DbContext
    {
        public PurpleSquirrelEntities()
            : base("name=PurpleSquirrelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Recruit> Recruits { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TemporaryEmployee> TemporaryEmployees { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
