//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruit
    {
        public int ID { get; set; }
        public string CandidateName { get; set; }
        public string Post { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> Bonus { get; set; }
        public int ReferralID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
    }
}
