//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int ReferralID { get; set; }
        public int EmployeeID { get; set; }
        public int JobID { get; set; }
        public string Experience { get; set; }
        public string CandidateName { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> ReferDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ResumeID { get; set; }
    }
}
